name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: sum test
      id: sum-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: sum test
        setup-command: ''
        command: python3 sum.py
        input: '5'
        expected-output: '15'
        comparison-method: contains
        timeout: 10
        max-score: 20
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SUM-TEST_RESULTS: "${{steps.sum-test.outputs.result}}"
      with:
        runners: sum-test
